### PR TITLE
Use pyproject.toml, bundle config files and make CLI available

### PR DESCRIPTION
**Pull request by AlexandreDecan**

### CODE REVIEW

**Comment by AlexandreDecan** [comment]
Please also note that package name is "ghamap" while repository name is "ghmap". This could lead to some confusion. I suggest being consistent here.

**Comment by uhourri** [comment]
should we give the same name?

**Comment by AlexandreDecan** [comment]
For consistency, yes
Is there any reason to have different names?

**Comment by uhourri** [comment]
there's no reason, it was you who added 'ghamap', the old version has only 'ghmap' as name

**Comment by AlexandreDecan** [comment]
Oh sorry, I changed the name by mistake. I don't care about the name to be honest. Just be consistent and fix my change then :-)

**Pull request merged**
